---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователь должен иметь возможность войти в личный кабинет.
  - Пользователь должен иметь возможность выйти из личного кабинета.
  - Пользователь должен иметь возможность принять участие в игре без регистрации.
  - Пользователь должен иметь возможность восстановить пароль.
  - Пользователь должен иметь возможность искать конкретного пользователя в списке.
  - Пользователь должен иметь возможность просматривать задачи.
  - Пользователь должен иметь возможность создать новую задачу.
  - Пользователь должен иметь возможность изменить свои данные в личном кабинете.
  - Пользователь должен иметь возможность просматривать информацию о турнирах.
  - Пользователь должен иметь возможность создать турнир.
  - Пользователь должен иметь возможность просматривать рейтинг пользователей.
  - Пользователь должен иметь возможность просматривать завершенные игры.
  - Пользователь должен иметь возможность в личном кабинете вести переписку в чате.
  - Пользователь должен иметь возможность во время переписки использовать смайлы.
  - Пользователь должен иметь возможность пригласить другого пользователя в игру.
  - Пользователь должен иметь возможность отправить личное сообщение другому пользователю.
  - Пользователь имеет возможность создать игру.
  - Пользователь имеет возможность принять участие в созданной игре.
  - Пользователь должен иметь возможность выбрать во время игры язык программирования. 
  - Пользователь должен иметь возможность во время игры просматривать задачу на английском и русском языках.
  - Пользователь должен иметь возможность во время игры проверить решение.
  - Пользователь должен иметь возможность во время игры просматривать свой редактор и редактор соперника.
  - Пользователь должен иметь возможность просмотреть повтор игры.
  - Пользователь должен иметь возможность во время игры сбросить редактор.
  - Пользователь должен иметь возможность предложить реванш сопернику.
  - Пользователь должен иметь возможность сдаться во время игры.
  - Пользователь должен иметь возможность из игры вернуться в личный кабинет.
  - В форме регистрации поле "Nickname" может содержать буквы, цифры и символы подчеркивания, должен начинаться с латинской буквы и должен быть от 3 до 16 символов
  - В форме регистрации поле "Password Confirmation" должен быть от 6 до 16 символов и совпадать с полем " Password"

non-functional:
  - Интерфейс сайта должен быть адаптивным и корректно отображаться на мобильных устройствах.
  - Сайт должен сохранять стабильность при высокой нагрузке (не менее 1000 одновременных пользователей).
  - Все ключевые функции работают стабильно в актуальных версиях популярных браузеров (Chrome, Firefox, Safari, Edge).
  - Время отклика интерфейса при взаимодействии не превышает 3 секунд.
  - Веб-приложение должно быть локализовано минимум на два языка - русский и английский.

implicit:
  - Сайт должен обеспечивать безопасность данных пользователя.
  - Сайт должен использовать HTTPS для защищённого соединения.
  - Сайт должен быть протестирован на совместимость с актуальными версиями популярных браузеров (Chrome, Firefox, Safari и др.).
  - Удобство использования - элементы интерфейса размещаются интуитивно, навигация понятна без инструкции.
  - Возможность расширения - система поддерживает добавление новых задач, языков программирования и игровых режимов.
